In [126]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [127]:
dataset = pd.read_csv('dataset/exams.csv')
dataset.drop(["race/ethnicity"], axis=1, inplace=True)
dataset.drop(["lunch"], axis=1, inplace=True)
dataset['gender'].replace( 'female',0,inplace=True)
dataset['gender'].replace( 'male',1,inplace=True)
dataset

gender parental level of education test preparation course  math score  \
0         1                 high school               completed          67   
1         0            some high school                    none          40   
2         1                some college                    none          59   
3         1                 high school                    none          77   
4         1          associate's degree               completed          78   
..      ...                         ...                     ...         ...   
995       1                 high school                    none          73   
996       1          associate's degree               completed          85   
997       0            some high school                    none          32   
998       0                some college                    none          73   
999       1                some college               completed          65   

     reading score  writing score  
0               67             63  
1               59             55  
2               60             50  
3               78             68  
4               73             68  
..             ...            ...  
995             70             65  
996             91             92  
997             35             41  
998             74             82  
999             60             62  

[1000 rows x 6 columns]

In [128]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(dataset['parental level of education'])
eductionLevel = le.transform(dataset['parental level of education'])
dataset['parental level of education'] = eductionLevel


In [129]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(dataset['test preparation course'])
eductionLevel = le.transform(dataset['test preparation course'])
dataset['test preparation course'] = eductionLevel

In [149]:
le.transform( ['none', 'completed'])

array([1, 0])

In [130]:
dataset.head()

gender  parental level of education  test preparation course  math score  \
0       1                            2                        0          67   
1       0                            5                        1          40   
2       1                            4                        1          59   
3       1                            2                        1          77   
4       1                            0                        0          78   

   reading score  writing score  
0             67             63  
1             59             55  
2             60             50  
3             78             68  
4             73             68

In [131]:
y = dataset.iloc[:,2].values
y
dataset.drop(["test preparation course"], axis=1, inplace=True)


In [132]:
X = dataset.iloc[:, :].values
X

array([[ 1,  2, 67, 67, 63],
       [ 0,  5, 40, 59, 55],
       [ 1,  4, 59, 60, 50],
       ...,
       [ 0,  5, 32, 35, 41],
       [ 0,  4, 73, 74, 82],
       [ 1,  4, 65, 60, 62]], dtype=int64)

In [133]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)


In [134]:
from sklearn.svm import SVC
clf =  SVC(gamma='auto')
clf.fit(X_train, y_train)

SVC(gamma='auto')

In [135]:
predicts =clf.predict(X_test)

In [136]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicts)

In [137]:
cm

array([[  9, 102],
       [ 11, 208]], dtype=int64)

In [154]:
tn, fp, fn, tp = confusion_matrix(y_test, predicts).ravel()
tn, fp,fn,fp

(9, 102, 11, 102)

In [153]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicts)

0.6575757575757576

In [152]:
count = 0
for i in range(len(predicts)):
    if predicts[i] == y_test[i]:
        count +=1
print(count, len(predicts))

217 330


In [146]:
predicts[0]

1